<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>WinCleaner</AssemblyName>
    <RootNamespace>WinCleaner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinCleaner.Core\WinCleaner.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\AppConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>